# Generated by Django 5.0.3 on 2024-03-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HumanResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_staff', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('qualification', models.CharField(choices=[('shs', 'shs'), ('diploma', 'diploma'), ('bachelors degree', 'bachelors degree')], max_length=50)),
                ('name_of_department', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('date_of_appointment', models.DateField()),
                ('image_of_staff', models.FileField(upload_to='')),
            ],
        ),
    ]
