# Generated by Django 5.0.3 on 2024-03-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanresource', '0002_humanresource_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humanresource',
            name='image_of_staff',
            field=models.ImageField(upload_to='staff_images/'),
        ),
        migrations.AlterField(
            model_name='humanresource',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
