# Generated by Django 5.0.3 on 2024-03-15 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('humanresource', '0003_alter_humanresource_image_of_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humanresource',
            name='name_of_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department'),
        ),
    ]
