# Generated by Django 5.0.3 on 2024-03-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.FloatField()),
                ('phone', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('age_group', models.CharField(choices=[('0-28', '0-28 days'), ('1-11', '1-11 months'), ('1-4', '1-4 years'), ('5-9', '5-9 years'), ('10-14', '10-14 years'), ('15-17', '15-17 years'), ('18-19', '18-19 years'), ('20-34', '20-34 years'), ('35-49', '35-49 years'), ('50-59', '50-59 years'), ('60-69', '60-69 years'), ('70+', '70 yrs & Above')], max_length=20)),
                ('NHIS_number', models.CharField(default='none', max_length=30)),
                ('client_type', models.CharField(default='none', max_length=50)),
                ('client_status', models.CharField(default='none', max_length=50)),
                ('occupation', models.CharField(default='none', max_length=50)),
                ('address', models.CharField(default='none', max_length=50)),
                ('date_of_visit', models.DateField()),
                ('name_of_guardian', models.CharField(default='none', max_length=50)),
                ('relation_with_guardian', models.CharField(default='none', max_length=50)),
                ('contact_of_guardian', models.CharField(default='none', max_length=50)),
            ],
        ),
    ]
