# Generated by Django 5.0.3 on 2024-03-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='client_status',
            field=models.CharField(choices=[('insured', 'insured'), ('non-in', 'non-insured')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='client_type',
            field=models.CharField(choices=[('New client', 'new client'), ('old client', 'old client')], max_length=20),
        ),
    ]
