# Generated by Django 5.0.3 on 2024-03-12 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0002_alter_patientrecord_client_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_category', models.CharField(choices=[('OPD consultation', 'OPD consultation'), ('Dental consultation', 'Dental consultation'), ('Eye consultation', 'Eye consultation')], max_length=100)),
                ('service_price', models.FloatField()),
                ('service_requested_by', models.CharField(max_length=100)),
                ('service_requested_on', models.DateField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient_records.patientrecord')),
            ],
        ),
    ]
