# Generated by Django 5.0.3 on 2024-03-12 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0003_servicerequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='service_requested_by',
            new_name='requested_by',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='service_requested_on',
            new_name='requested_on',
        ),
    ]
