# Generated by Django 5.0.3 on 2024-03-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0004_rename_service_requested_by_servicerequest_requested_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='service_category',
            field=models.CharField(choices=[('OPD consultation', 'OPD consultation'), ('Dental consultation', 'Dental consultation'), ('Eye consultation', 'Eye consultation'), ('ANC', 'ANC')], max_length=20),
        ),
    ]
