# Generated by Django 5.0.3 on 2024-03-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0005_alter_servicerequest_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='client_status',
            field=models.CharField(choices=[('insured', 'insured'), ('non-insured', 'non-insured')], max_length=20),
        ),
    ]
