# Generated by Django 5.0.3 on 2024-03-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0007_alter_patientrecord_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='level_of_education',
            field=models.CharField(choices=[('no formal education', 'no formal education'), ('primary', 'primary'), ('JHS', 'JHS'), ('SHS/Technical/Vocational', 'SHS/Technical/Vocational'), ('tertiary', 'tertiary'), ('other', 'other')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='occupation',
            field=models.CharField(choices=[('unemployed', 'unemployed'), ('student', 'student'), ('farming', 'farming'), ('trading', 'trading'), ('artisan(hairdresser,seamstress)', 'artisan(hairdresser,seamstress)'), ('civil servant', 'civil servant'), ('others', 'others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='relation_with_guardian',
            field=models.CharField(choices=[('parent', 'parent'), ('sibling', 'sibling'), ('uncle/aunt', 'uncle/aunt'), ('grandparent', 'grandparent'), ('nephew/niece', 'nephew/niece'), ('other', 'other')], max_length=50),
        ),
    ]
