# Generated by Django 5.0.3 on 2024-03-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0008_patientrecord_level_of_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='other_names',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
