# Generated by Django 5.0.3 on 2024-03-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0009_patientrecord_other_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='age_group',
            field=models.CharField(choices=[('0-28 days', '0-28 days'), ('1-11 months', '1-11 months'), ('1-4 years', '1-4 years'), ('5-9 years', '5-9 years'), ('10-14 years', '10-14 years'), ('15-17 years', '15-17 years'), ('18-19 years', '18-19 years'), ('20-34 years', '20-34 years'), ('35-49 years', '35-49 years'), ('50-59 years', '50-59 years'), ('60-69 years', '60-69 years'), ('70+ yrs & Above', '70 yrs & Above')], max_length=20),
        ),
    ]
