# Generated by Django 5.0.3 on 2024-03-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0010_alter_patientrecord_age_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='marital_status',
            field=models.CharField(choices=[('single', 'single'), ('married', 'married'), ('divorced', 'divorced'), ('widow', 'widow'), ('widower', 'widower'), ('other', 'other')], default='none', max_length=50),
        ),
    ]
