# Generated by Django 5.0.3 on 2024-03-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0011_patientrecord_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='age',
            field=models.IntegerField(),
        ),
    ]
