# Generated by Django 5.0.3 on 2024-03-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0013_patientrecord_age_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='age_type',
            field=models.CharField(choices=[('days', 'days'), ('months', 'months'), ('years', 'years')], default='none', max_length=20),
        ),
    ]
