# Generated by Django 5.0.3 on 2024-03-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('service_price', models.FloatField()),
                ('last_updated', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
