# Generated by Django 5.0.3 on 2024-03-13 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_department', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('last_updated', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
