# Generated by Django 5.0.3 on 2024-03-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_diagnosis', models.DateField()),
                ('provisional_diagnosis', models.CharField(max_length=50)),
                ('principal_diagnosis', models.CharField(max_length=50)),
            ],
        ),
    ]
