# Generated by Django 5.0.3 on 2024-03-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultingroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultingroom',
            name='clinical_notes',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='notes',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='consultingroom',
            name='other_diagnosis',
            field=models.CharField(max_length=100),
        ),
    ]
