# Generated by Django 5.0.3 on 2024-03-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultingroom', '0003_consultingroom_age_consultingroom_age_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultingroom',
            name='age',
        ),
    ]
