# Generated by Django 5.0.3 on 2024-03-23 17:12

import consultingroom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultingroom', '0004_remove_consultingroom_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultingroom',
            name='age',
            field=models.IntegerField(default=consultingroom.models.get_default_age),
        ),
        migrations.AlterField(
            model_name='consultingroom',
            name='age_type',
            field=models.CharField(choices=[('days', 'days'), ('months', 'months'), ('years', 'years')], default='years', max_length=50),
        ),
    ]
